image: gcc

build:
  stage: build
  before_script:
    - sudo apt update && sudo apt -y install make cmake clang-tidy
    - mkdir build && cd build
  script:
    - cmake ..
    - make
    - cpack
  artifacts:
    paths:
      - build/src/ppspp
      - build/libppspp/libppspp.so
      - build/*.deb

#test:
#  stage: test
#  script:
#    - ./runmytests.sh
